Insert into C##NOMASACCIDENTES.CONTRATO_CLIENTE (RUBRO_ID_RUBRO,COMUNA_ID_COMUNA,CLIENTE,PROFESIONAL) values ('13','1','1738132228','Profesional 2');
Insert into C##NOMASACCIDENTES.CONTRATO_CLIENTE (RUBRO_ID_RUBRO,COMUNA_ID_COMUNA,CLIENTE,PROFESIONAL) values ('12','1','123123123','Profesional 1');

Insert into C##NOMASACCIDENTES.ACCIDENTE (FECHA_ACC,GRAVEDAD_ID_GRAVEDAD,CONTRATO_CLIENTE_ID_CONTRATO,DETALLE_ACCIDENTE) values ('2021-11-13','4','1','sdsdsd');
Insert into C##NOMASACCIDENTES.ACCIDENTE (FECHA_ACC,GRAVEDAD_ID_GRAVEDAD,CONTRATO_CLIENTE_ID_CONTRATO,DETALLE_ACCIDENTE) values ('2021-11-12','1','2','sddsd');
Insert into C##NOMASACCIDENTES.ACCIDENTE (FECHA_ACC,GRAVEDAD_ID_GRAVEDAD,CONTRATO_CLIENTE_ID_CONTRATO,DETALLE_ACCIDENTE) values ('2021-11-12','2',3,'fsfsdf');
Insert into C##NOMASACCIDENTES.ACCIDENTE (FECHA_ACC,GRAVEDAD_ID_GRAVEDAD,CONTRATO_CLIENTE_ID_CONTRATO,DETALLE_ACCIDENTE) values ('2021-11-12','3','2','asdad');
Insert into C##NOMASACCIDENTES.ACCIDENTE (FECHA_ACC,GRAVEDAD_ID_GRAVEDAD,CONTRATO_CLIENTE_ID_CONTRATO,DETALLE_ACCIDENTE) values ('2021-11-12','3','2','asdad');
Insert into C##NOMASACCIDENTES.ACCIDENTE (FECHA_ACC,GRAVEDAD_ID_GRAVEDAD,CONTRATO_CLIENTE_ID_CONTRATO,DETALLE_ACCIDENTE) values ('2021-11-12','2','2','sdfsdf');
Insert into C##NOMASACCIDENTES.ACCIDENTE (FECHA_ACC,GRAVEDAD_ID_GRAVEDAD,CONTRATO_CLIENTE_ID_CONTRATO,DETALLE_ACCIDENTE) values ('2021-11-12','1',3,'fgdfgdfg');
Insert into C##NOMASACCIDENTES.ACCIDENTE (FECHA_ACC,GRAVEDAD_ID_GRAVEDAD,CONTRATO_CLIENTE_ID_CONTRATO,DETALLE_ACCIDENTE) values ('2021-11-12','1','1','fgdfg');

Insert into C##NOMASACCIDENTES.CAPACITACION (NOMBRE_CAP) values ('Prevencion de accidentes en bodegas');
Insert into C##NOMASACCIDENTES.CAPACITACION (NOMBRE_CAP) values ('Prevencion de accidentes en altura');
Insert into C##NOMASACCIDENTES.CAPACITACION (NOMBRE_CAP) values ('Prevencion de accidentes qui­micos');

Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values ('3','2021-11-30','cliente2@cliente.cl');
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values ('2','2021-11-15','cliente@cliente.cl');
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values ('4','2021-11-27','cliente@cliente.cl');
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values ('3','2021-11-07','cliente@cliente.cl');
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values ('2',null,'cliente@cliente.cl');
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values ('2','2021-11-28','cliente@cliente.cl');
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values ('3','2021-11-28','cliente@cliente.cl');
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values ('2','2021-11-26','cliente2@cliente.cl');
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);
Insert into C##NOMASACCIDENTES.DETALLE_CAP (CAPACITACION_ID_CAPACITACION,FECHA_CAP,CLIENTE) values (null,null,null);

Insert into C##NOMASACCIDENTES.EMPLEADO (NOMBRE_COMPLETO,RUT_EMP,DETALLE_CAP_ID_DETALLE_CAP) values ('Pepito tapia','12123123k','1');
Insert into C##NOMASACCIDENTES.EMPLEADO (NOMBRE_COMPLETO,RUT_EMP,DETALLE_CAP_ID_DETALLE_CAP) values ('Armando Castillos','131321320','1');
Insert into C##NOMASACCIDENTES.EMPLEADO (NOMBRE_COMPLETO,RUT_EMP,DETALLE_CAP_ID_DETALLE_CAP) values ('Joselo Mucho','212121218','1');
Insert into C##NOMASACCIDENTES.EMPLEADO (NOMBRE_COMPLETO,RUT_EMP,DETALLE_CAP_ID_DETALLE_CAP) values ('empleado 1','1738132228','158');
Insert into C##NOMASACCIDENTES.EMPLEADO (NOMBRE_COMPLETO,RUT_EMP,DETALLE_CAP_ID_DETALLE_CAP) values ('empleado 2','12312213','158');
Insert into C##NOMASACCIDENTES.EMPLEADO (NOMBRE_COMPLETO,RUT_EMP,DETALLE_CAP_ID_DETALLE_CAP) values ('asdasdasd','1738132228','2');
Insert into C##NOMASACCIDENTES.EMPLEADO (NOMBRE_COMPLETO,RUT_EMP,DETALLE_CAP_ID_DETALLE_CAP) values ('pablo 1','1738132228','1');
Insert into C##NOMASACCIDENTES.EMPLEADO (NOMBRE_COMPLETO,RUT_EMP,DETALLE_CAP_ID_DETALLE_CAP) values ('pablo 2','1738132228','1');
Insert into C##NOMASACCIDENTES.EMPLEADO (NOMBRE_COMPLETO,RUT_EMP,DETALLE_CAP_ID_DETALLE_CAP) values ('pablo 3','1738132228','1');
Insert into C##NOMASACCIDENTES.EMPLEADO (NOMBRE_COMPLETO,RUT_EMP,DETALLE_CAP_ID_DETALLE_CAP) values ('pablo 4','1738132228','1');

Insert into C##NOMASACCIDENTES.PLAN (SERVICIO_ID_SERVICIO,SERVICIO_EXTRA_ID_SERV_EX,CLIENTE) values ('1',null,'1738132228');
Insert into C##NOMASACCIDENTES.PLAN (SERVICIO_ID_SERVICIO,SERVICIO_EXTRA_ID_SERV_EX,CLIENTE) values ('1',null,'123123123');
Insert into C##NOMASACCIDENTES.PLAN (SERVICIO_ID_SERVICIO,SERVICIO_EXTRA_ID_SERV_EX,CLIENTE) values ('4',null,'123123123');
Insert into C##NOMASACCIDENTES.PLAN (SERVICIO_ID_SERVICIO,SERVICIO_EXTRA_ID_SERV_EX,CLIENTE) values ('4',null,'123123123');
