# Generated by Django 3.2.7 on 2021-10-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211006_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
        migrations.AddField(
            model_name='user',
            name='es_administrador',
            field=models.BooleanField(default=False, verbose_name='Es administrador'),
        ),
        migrations.AddField(
            model_name='user',
            name='es_cliente',
            field=models.BooleanField(default=False, verbose_name='Es cliente'),
        ),
        migrations.AddField(
            model_name='user',
            name='es_profesional',
            field=models.BooleanField(default=False, verbose_name='Es profesional'),
        ),
    ]
