# Generated by Django 3.2.7 on 2021-10-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
