# Generated by Django 3.2.7 on 2021-10-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211023_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='razon_social',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
